#!/bin/bash

shopt -s extglob

ROOT=$1
DATE=$(date +%y%m%d)
DEST=$2/liims$DATE

if [[ ! -d "$ROOT" || ! -d "$2" ]]; then
    echo "./deploy ROOT DEST" 1>&2
    exit 1
fi

mkdir $DEST
mv $1/boot/vmlinuz* $DEST/vmlinuz
rm $1/boot/initramfs*-fallback.img
mv $1/boot/initramfs*.img $DEST/initrd.img
rm -rf $1/usr/share/locale/!(zh_CN|en|en_US)
rm -rf $1/usr/share/gtk-docs/*
rm -rf $1/usr/share/doc/*
rm -rf $1/usr/share/man/*

mksquashfs $1/ $DEST/$DEST.sfs -comp lzo -Xcompression-level 9 -b 32k
