#!/bin/bash

shopt -s extglob

ROOT="$1"
DATE="$(date +%y%m%d)"
DEST="$2/liims"

if [[ ! -d "$ROOT" || ! -d "$2" ]]; then
    echo "./deploy ROOT DEST" >&2
    exit 1
fi

KERNEL=$(ls "$ROOT"/boot | grep -m1 -Po "^vmlinuz-\K\S+")

mkdir "$DEST"
cp "$ROOT/boot/vmlinuz-$KERNEL" "$DEST/vmlinuz"
cp "$ROOT/boot/initrd.img-$KERNEL" "$DEST/initrd.img"
rm -rf "$ROOT"/usr/share/locale/!(zh_CN|en|en_US)

mksquashfs "$ROOT"/ "$DEST"/root.sfs -comp zstd -Xcompression-level 19 -b 128k \
    -e 'boot/' \
    -e 'usr/share/gtk-docs/' \
    -e 'usr/share/doc/' \
    -e 'usr/share/man/'
