#!/bin/bash

set -e
shopt -s extglob

ROOT="$1"
DEST="$2"

if [[ ! -d "$ROOT" || ! -d "$DEST" ]]; then
    echo "./deploy ROOT DEST" >&2
    exit 1
fi

KERNEL=$(basename "$(readlink "$ROOT/vmlinuz")")
KERNEL=${KERNEL#vmlinuz-}
test -f "$ROOT/boot/vmlinuz-$KERNEL"

mkdir -p "$DEST"
cp "$ROOT/boot/vmlinuz-$KERNEL" "$DEST/vmlinuz"
cp "$ROOT/boot/initrd.img-$KERNEL" "$DEST/initrd.img"
rm -rf "$ROOT"/usr/share/locale/!(zh_CN|en|en_US)

mksquashfs "$ROOT"/ "$DEST"/root.sfs -comp zstd -Xcompression-level 14 -b 128k \
    -e 'boot/' \
    -e 'usr/share/gtk-docs/' \
    -e 'usr/share/doc/' \
    -e 'usr/share/man/'

(cd "$DEST" && sha256sum vmlinuz initrd.img root.sfs > SHA256SUMS)
