#!/bin/bash

set -e
BASE="$(dirname "$0")"

chdo() {
    chroot "$ROOT" "$@"
} 

enserv() {
    chroot "$ROOT" systemctl enable "$@"
}

inspkg() {
    DEBIAN_FRONTEND=noninteractive chroot "$ROOT" apt-get install -o Acquire::http::Pipeline-Depth=\"0\" --no-install-recommends --yes "$@"
}

check_sha256() {
    local file="$1"
    local sha256="$2"
    if [[ "$sha256" = $(sha256sum "$file" | cut -d ' ' -f 1) ]]; then
        return
    else
        echo "$file is corrupt."
        exit 1
    fi
}

ROOT="$1"
LIIMSUSER="liims"

if [ ! -d "$ROOT" ]; then
    echo "$ROOT is not a directory."
    exit 1
elif [ $(id -u) -ne 0 ]; then
    echo "You are not root!"
    exit 1
fi

# root password
if [ -f "$BASE/.rootpasswd" ]; then
    ROOTPASSWD=$(<"$BASE/.rootpasswd")
else
    while true; do
        echo -e "root password: "
        read -s ROOTPASSWD
        echo -e "root password again: "
        read -s ROOTPASSWD2

        [ "$ROOTPASSWD" == "$ROOTPASSWD2" ] && break
    done
    unset ROOTPASSWD2
fi

# debootstrap
debootstrap bullseye "$ROOT" http://mirrors.ustc.edu.cn/debian/
mount proc "$ROOT/proc" -t proc
mount sysfs "$ROOT/sys" -t sysfs

# apt update
install -Dm 644 "$BASE/etc/apt/sources.list" "$ROOT/etc/apt/sources.list"
chdo apt update

# install packages
# following packages may need interactive operations and should take care
# Install X-related packages
inspkg xterm xserver-xorg xserver-xorg-video-vesa xserver-xorg-video-nouveau\
    xserver-xorg-video-intel xserver-xorg-video-fbdev xcompmgr xauth
# Install CLI tools
inspkg busybox cron dhcpcd5 dnsutils htop inetutils-ftp inetutils-ping \
    inetutils-telnet iptables iptables-persistent iproute2 \
    iputils-arping iputils-clockdiff iputils-tracepath iso-codes \
    initramfs-tools ndisc6 netdata nyancat openssh-client openssh-server \
    procps rsync scrot sed tar unionfs-fuse usbutils vim
# Install desktop components
inspkg fcitx fcitx-frontend-gtk2 fcitx-frontend-gtk3 gnome-icon-theme \
    gnome-themes-standard openbox slim fonts-arphic-uming fonts-droid-fallback \
    fonts-wqy-zenhei fbpanel xfonts-terminus fcitx-pinyin fcitx-table-wubi fcitx-ui-classic
# Install misc packages
inspkg bash-completion locales net-tools zstd
# Install extra packages that not in original list
inspkg x11-utils libcurl4 curl ca-certificates dbus-x11 jq xfonts-base xfonts-intl-chinese \
    x11-xserver-utils
# Install customized midori
curl https://ftp.lug.ustc.edu.cn/~taoky/midori-liims_9.0-SNAPSHOT-1640974719_amd64.deb > $ROOT/tmp/midori.deb
check_sha256 $ROOT/tmp/midori.deb "a82704e17a49071b45ccb2c7c3d4f5ecfbd2759a7942e539efd4ac4742684f4e"
inspkg /tmp/midori.deb
# Install sogoupinyin
# ref: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fcitx-sogoupinyin
curl -s https://pinyin.sogou.com/linux/ | grep -Po "https://.*?/sogoupinyin_3.4.0.9700_amd64.deb" | xargs curl -o "$ROOT/tmp/sogoupinyin.deb"
check_sha256 $ROOT/tmp/sogoupinyin.deb "0a8de6e87c1402db49869754fa08dd58c448cd44f06b73b825debe7bea27d74d"
inspkg libasound2 libgomp1  # missing deps in sogoupinyin
inspkg /tmp/sogoupinyin.deb

# Cleanup deb files
rm -f "$ROOT"/tmp/*.deb

# Assistant scripts and programs
mkdir -p "$ROOT/liims/bin"
echo 'export PATH=$PATH:/liims/bin' > "$ROOT/etc/profile.d/liims.sh"
echo "export LIIMSUSER=$LIIMSUSER" >> "$ROOT/etc/profile.d/liims.sh"

for script in "$BASE"/bin/*.sh; do
    install -Dm 755 "$script" "$ROOT/liims/bin"
done

unset CFLAGS
cc "$BASE/bin/xidle.c" -o "$ROOT/liims/bin/xidle" -O2 -s -lX11 -lXext -lXss

# SSH login for root
cp "$BASE/etc/ssh"/* "$ROOT/etc/ssh"
printf "root:%s\n" "$ROOTPASSWD" | chdo chpasswd
enserv ssh

# resolv.conf
cp "$BASE/etc/resolv.conf" "$ROOT/etc/resolv.conf"
cat "$BASE/etc/hosts" >> "$ROOT/etc/hosts"

# dhcpcd
enserv dhcpcd

# time and NTP
TZ=Asia/Shanghai
echo "$TZ" > "$ROOT/etc/timezone"
chdo ln -sfn "/usr/share/zoneinfo/$TZ" /etc/localtime
echo -e "[Time]\nNTP=time.ustc.edu.cn" > "$ROOT/etc/systemd/timesyncd.conf"
enserv systemd-timesyncd.service

# locale
echo -e "en_US.UTF-8 UTF-8\nzh_CN.GBK GBK\nzh_CN.UTF-8 UTF-8" > \
        "$ROOT/etc/locale.gen"
chdo locale-gen

# iptables
mkdir -p "$ROOT/etc/iptables"
cp "$BASE/etc/iptables/iptables.rules" "$ROOT/etc/iptables/rules.v4"
cp "$BASE/etc/iptables/ip6tables.rules" "$ROOT/etc/iptables/rules.v6"
enserv iptables.service

# crontab
cp "$BASE/etc/root.crontab" "$ROOT/tmp/"
chdo crontab "/tmp/root.crontab"
enserv cron

# slim
cp "$BASE/etc/slim.conf" "$ROOT/etc/"
chdo systemctl set-default graphical.target

# netdata
cp -r "$BASE/etc/netdata/" "$ROOT/etc/"
chdo chown -R netdata:netdata "/usr/share/netdata/web/"
enserv netdata

# prevent systemd from changing network interface name
chdo ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# user specific
chdo userdel -fr "$LIIMSUSER" || true
chdo useradd -m -g users -s /bin/bash "$LIIMSUSER"
cp -r "$BASE/user/." "$ROOT/home/$LIIMSUSER"
chdo chown -R "$LIIMSUSER" "/home/$LIIMSUSER"

# prevent sogou from modifying fcitx config
chmod a-w "$ROOT/home/$LIIMSUSER/.config/fcitx/"*

# hostname
echo "liims" > "$ROOT/etc/hostname"

# Remove unused locales
inspkg localepurge
install -Dm644 "$BASE/etc/locale.nopurge" "$ROOT/etc/locale.nopurge"
chdo localepurge
chdo apt purge -y --autoremove localepurge

# kernel
install -Dm644 "$BASE/initramfs-tools/initramfs.conf" "$ROOT/etc/initramfs-tools/initramfs.conf"
install -Dm644 "$BASE/initramfs-tools/modules" "$ROOT/etc/initramfs-tools/modules"
install -Dm755 "$BASE/initramfs-tools/scripts/init-bottom/overlay.sh" "$ROOT/etc/initramfs-tools/scripts/init-bottom/overlay.sh"
inspkg linux-image-amd64 firmware-linux

# Remove unused docs
rm -rf "$ROOT/usr/share/doc/"*

# cleanup
umount "$ROOT/proc"
umount "$ROOT/sys"
chdo apt-get clean
