#!/bin/bash -e

sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

apt-get update
apt-get upgrade

apt-get install -o Acquire::http::Pipeline-Depth="0" --no-install-recommends --yes \
    debootstrap build-essential libcurl4-openssl-dev libx11-dev libxext-dev libxss-dev \
    curl ca-certificates

apt-get clean
