#!/bin/bash

sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

apt-get update

apt-get upgrade

apt-get install --yes debootstrap build-essential libcurl4-openssl-dev libx11-dev libxext-dev libxss-dev

apt-get clean
