#!/bin/bash

echo 'Server = http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

cat << EOF >> /etc/pacman.conf
[archlinuxcn]
SigLevel = Optional TrustedOnly
Server = http://mirrors.ustc.edu.cn/archlinuxcn/x86_64
EOF

pacman -Syy && pacman -S --noconfirm archlinuxcn-keyring

pacman -Syu --noconfirm

cd /opt/liims
echo $ROOT_PASSWORD > .rootpasswd
mkdir -p /srv/root
mkdir -p /srv/dest
./liimstrap /srv/root
./deploy /srv/root /srv/dest

