#!/bin/bash

sed -Ei 's/(deb|security)\.debian\.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

apt-get update
apt-get upgrade

cd /opt/liims
printf "%s\n" "$ROOT_PASSWORD" > .rootpasswd
# mkdir -p /srv/root
mkdir -p /srv/dest
./liimstrap /srv/dest
# ./deploy /srv/root /srv/dest
