name: Docker Image CI

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build \
          --build-arg APT_SOURCE=http://deb.debian.org \
          -t ustclug/liimstrap:liims-2 .

    - name: Build liimstrap image
      env:
        ROOT_PASSWORD: ${{ secrets.LIIMSTRAP_ROOT_PASSWORD }}
        MIDORI_URL: ${{ secrets.MIDORI_URL }}
        SOGOUPINYIN_URL: ${{ secrets.SOGOUPINYIN_URL }}
      run: |
        docker run --privileged --rm \
          -v /srv/dest:/srv/dest \
          -e GITHUB_RUN_NUMBER \
          -e ROOT_PASSWORD \
          -e MIDORI_URL \
          -e SOGOUPINYIN_URL \
          -e SQUASHFS=true \
          ustclug/liimstrap:liims-2

    - name: Generate release information
      id: release-info
      run: |
        echo "TAG_NAME=$(date +%y%m%d)-gh-$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release-info.outputs.TAG_NAME }}
        files: |
          /srv/dest/vmlinuz
          /srv/dest/initrd.img
          /srv/dest/root.sfs
