name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build liimstrap image
      run: docker build -t ustclug/liimstrap:liims-2 .

    - name: Pack to squashfs file
      env:
        ROOT_PASSWORD: ${{ secrets.LIIMSTRAP_ROOT_PASSWORD }}
        SOGOUPINYIN_URL: ${{ secrets.SOGOUPINYIN_URL }}
      run: |
        docker run --privileged --rm \
          -v /srv/dest:/srv/dest \
          -e ROOT_PASSWORD \
          -e SOGOUPINYIN_URL \
          -e SQUASHFS=true \
          ustclug/liimstrap:liims-2

    - name: Set release tag env
      run: |
        echo "TAG_NAME=$(date +'%Y-%m-%d')_$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /srv/dest/vmlinuz
          /srv/dest/initrd.img
          /srv/dest/root.sfs
        tag_name: ${{ env.TAG_NAME }}
